# Generated by Django 3.2.5 on 2021-07-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('priority', models.CharField(choices=[('Top', 'T'), ('medium', 'M'), ('Down', 'D')], max_length=10, unique=True, verbose_name='priority')),
                ('time_reached', models.TimeField(auto_now_add=True, verbose_name='Times hit task')),
                ('category', models.ManyToManyField(blank=True, related_name='categories', to='todo.Category')),
            ],
        ),
    ]
