# Generated by Django 3.2.5 on 2021-07-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('Top', 'Top'), ('medium', 'Medium'), ('Down', 'Down')], max_length=10, unique=True, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='time_reached',
            field=models.DateTimeField(verbose_name='Times hit task'),
        ),
    ]
