# Generated by Django 3.2.5 on 2021-07-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210729_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('Top', 'Top'), ('medium', 'Medium'), ('Down', 'Down')], max_length=10, verbose_name='priority'),
        ),
    ]
